### PR TITLE
Developer

### PR DESCRIPTION
**Pull request by gitnyasha**
**What does this PR do**
- Final pull request
- implemented stylelint
- tested index.html file on w3validator
- updated our read me file
- we have followed all the requirements as per the document required

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! WOW Project looks! :+1: The readme file is very descriptive!

### But your project still needs changes.

Kindly recommended checking HTML markup with this validator https://validator.w3.org/#validate_by_upload.

screenshot

Now it shows errors in your project

errors

 ### Also Page structure

#### Navigation bar
In the leftmost part here should be "Hamburger button"

#### Bottom part

* It should contain links to other articles with image previews on the leftmost side & It should contain links to more popular articles on the rightmost side

bottom

#### Navigation bar

* It should have a fixed position (it sticks to the top part of the screen), please add this property to your navbar

navbar

* As I can see you create different branches with a descriptive name, but please kindly recommended next time open pull request from a branch with a descriptive name too. Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). 
* Pull Request should have a meaningful title. Pleaase read more here [Professional Github repository](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

screen

I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes.

**Comment by kirokoNjenga** [comment]
**validator errors are all cleared **
@Anna-Myzukina  we check with the validator for errors and it's clear please do another fetch
image

**Comment by kirokoNjenga** [comment]
@Anna-Myzukina 
please check the update and advice

**Comment by shshamim63** [comment]
## Status :accept: [!! Accepted !!] :accept: 
___
Hi @gitnyasha  and @Samkiroko  :wave: ,
Awesome job on this project :clap: . No lint error, code looks clean, no commented code, project looks almost clone of the original one, descriptive readme and well described PR.Wow :open_mouth:.
Just got a suggestion. You could use the article tag on your project. That will definitely gonna increase the semantic HTML tag usability.
___
##### This :+1:  is from me. You can merge it. And don't forget to fill the project completion form.
___
## :herb:  Happy Coding :herb: 
### Shakhawat Hossain

**Pull request merged**
